name: 'Deploy'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
  infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    env:
      resourceGroupName: static-web-app
      resourceGroupLocation: "westeurope"
      githubRepository: ${{ github.repository }}
      githubUrl: "https://github.com"
      appName: "mcanete"
    environment: production
    steps:
    - uses: actions/checkout@v2    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure Bicep Build
      run: |
        az bicep build --file infrastructure/main.bicep
    - name: Deploy Azure ARM
      uses: Azure/CLI@v1
      with:
        azcliversion: 2.23.0
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.resourceGroupName }} --location ${{ env.resourceGroupLocation }}
          az deployment group create -f infrastructure/main.json --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} -g ${{ env.resourceGroupName }} --parameters appName='${{ env.appName }}' repositoryUrl='${{ env.githubUrl }}/${{ env.githubRepository }}' repositoryToken='${{ secrets.GITHUB_TOKEN }}'

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    needs: infrastructure
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    needs: infrastructure
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
